### ISSUE TITLE
Fine Focus Spider Nacelle Tweak

### ISSUE THREAD

**Issue by irwtdvoys** [XVIIarcano/Galileo-Microscope#1]
The chamfer is missing from the bottom of two of the nacelle sliders. Caused a but of extra friction on mine until I cleaned it up.

![nacelle](https://github.com/XVIIarcano/Galileo-Microscope/assets/1695516/a9b71673-6daa-499b-b5de-0a6a70b321ad)

**Comment by XVIIarcano** [comment]
Ouch, I didn't notice this, not even when I printed the parts. I guess something in my specific prints (I don't remember if I have elephant foot compensation on or off for example) made it a bit more forgiving and mine did not get stuck.

Looking at the CAD file, this is a bit odd, because that chamfer should be the result of a single operation inf Fusion, pointed at the whole perimeter, I see now that for some reason it only produces the 1mm chamfer on one lobe, despite the others being identical all around. 

I can't screenshot while holding down CTRL, so here is a shot of the screen instead:
https://github.com/XVIIarcano/Galileo-Microscope/assets/131447789/13613849-8f98-47db-833a-8d518f26c60f

If I reduce the chamfer amount to 0.4 it manages to calculate the operation correctly. 
If I add a separate operation for the rest of the perimeter, it also works just fine.
Why all at once for 1mm is an issue is beyond my understanding...

I went for the separate 1mm operation and I have now updated the STLs and CAd files. 

Thanks a lot for pointing this out!
